/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author USUARIO
 */
import com.csvreader.CsvReader;
import gestor.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    int x,y;
    public static String estadoOperacion;
    DefaultListModel model2 = new DefaultListModel();
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        actulizarTablas();
        
        
            
    }
    public void actulizarTablas()
    {
        DefaultListModel model = new DefaultListModel();
        List<String> nombres = new ArrayList<>();
        String fileMETA = "filesBD\\META.bd"; 
        try {
            CsvReader ar = new CsvReader(fileMETA);
            model.clear();
            while(ar.readRecord()){
                model.addElement(ar.get(0));
            }
            ListaTablas.setModel(model);
        }
        catch(Exception io)
        {
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        BotonSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaTablas = new javax.swing.JList<>();
        BotonEjecutar = new javax.swing.JButton();
        ComandosTabla = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listascomando = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        SugerenciaTabla = new javax.swing.JComboBox<>();
        SugerenciaRegistro = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        mensajesConsola = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(844, 524));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSalir.setText("X");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 40, 20));

        ListaTablas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jScrollPane2.setViewportView(ListaTablas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 200, 410));

        BotonEjecutar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BotonEjecutar.setText("EJECUTAR COMANDO");
        BotonEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEjecutarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEjecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 230, 30));

        ComandosTabla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComandosTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComandosTablaActionPerformed(evt);
            }
        });
        getContentPane().add(ComandosTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 550, 40));

        listascomando.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jScrollPane1.setViewportView(listascomando);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 550, 110));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 550, 10));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 20, 440));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 550, 10));

        SugerenciaTabla.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        SugerenciaTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUGERENCIAS TABLAS", "Crear Tabla", "Modificar Tabla", "Eliminar Tabla", "Seleccionar Tabla", "JOIN - Unir Tablas" }));
        SugerenciaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SugerenciaTablaActionPerformed(evt);
            }
        });
        getContentPane().add(SugerenciaTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 240, 30));

        SugerenciaRegistro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        SugerenciaRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUGERENCIAS REGISTROS", "Crear Registro", "Modificar Registro", "Eliminar Registro", " " }));
        SugerenciaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SugerenciaRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(SugerenciaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 240, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mensajesConsola.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mensajesConsola.setForeground(new java.awt.Color(255, 0, 0));
        mensajesConsola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(mensajesConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 550, 40));

        jLabel6.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("              GESTOR DE BASE DE DATOS");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 550, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("             TABLAS");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 200, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  ACTIVIDADES");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 550, 30));

        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boxes_Teal.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 840, 520));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 840, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComandosTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComandosTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComandosTablaActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEjecutarActionPerformed
        // TODO add your handling code here:
        this.ejecutar();
        
    }//GEN-LAST:event_BotonEjecutarActionPerformed

    private void SugerenciaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SugerenciaTablaActionPerformed
        // TODO add your handling code here:
        this.Sugerencias();
    }//GEN-LAST:event_SugerenciaTablaActionPerformed

    private void SugerenciaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SugerenciaRegistroActionPerformed
        // TODO add your handling code here:
        this.Sugerencias1();
    }//GEN-LAST:event_SugerenciaRegistroActionPerformed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
       
        // TODO add your handling code here:
        x= evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        this.setLocation(this.getLocation().x + evt.getX()-x, this.getLocation().y + evt.getY()-y);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseDragged
    private void ejecutar()
    {
         long startTime = 0;
         long endTime = 0;
        try
        {
           mensajesConsola.setText("Por favor espere, esta operacion puede tardar unos segundos...");
           mensajesConsola.setForeground(Color.BLACK);
           estadoOperacion = null;
           startTime = System.currentTimeMillis();
           GestionBD gestion = new GestionBDProxy();
           Object []args = {ComandosTabla.getText()};
           gestion.Peticion(args);
        }
        catch(Exception io)
        {
            mensajesConsola.setText(io.getMessage());
            mensajesConsola.setForeground(Color.red);
        }
        if(estadoOperacion!=null){
            //Resultado de la operacion
            endTime= System.currentTimeMillis() ; 
            JOptionPane.showMessageDialog(null, "Tiempo en realizar la operacion: "  + Math.abs((startTime  - endTime )/1000)+" s.", "Info", JOptionPane.INFORMATION_MESSAGE);
            System.out.println(endTime);
            actulizarTablas();
            mensajesConsola.setText(estadoOperacion);
            mensajesConsola.setForeground(Color.blue);
            model2.addElement(estadoOperacion);
            listascomando.clearSelection();
            listascomando.setModel(model2);
            
        }
    }
    public void Sugerencias(){
       int op = SugerenciaTabla.getSelectedIndex();
       if(op == 0){
       ComandosTabla.setText("HOLA");
       }
       else if(op == 1){
       ComandosTabla.setText("CREAR TABLA nombre_tabla CAMPOS (campo1,...,campoN) CLAVE campo1 LONGITUD ##, ENCRIPTADO campo1,...,campoN");
       }
       else if(op == 2){
       ComandosTabla.setText("MODIFICAR TABLA nombre_tabla CAMPO nombre_campo POR nombre_campo");
       }
       else if(op == 3){
       ComandosTabla.setText("ELIMINAR TABLA nombre_tabla");
       }
       else if(op == 4){
       ComandosTabla.setText("SELECCIONAR DE nombre_tabla DONDE nombre_campo = “Algo” ORDENADO asc/desc VER número_registros");
       }
       else if(op == 5){
       ComandosTabla.setText("UNIR nombre_tabla1, nombre_tabla2 POR nombre_campo ORDENADO asc/desc VER número_registros");
       }
       
    }
    public void Sugerencias1(){  
       int op1 = SugerenciaRegistro.getSelectedIndex();

       if(op1 == 0){
       ComandosTabla.setText("");
       }
       else if(op1 == 1){
       ComandosTabla.setText("CREAR REGISTRO nombre_tabla VALOR vCampo1, vCampo2...., vCampoN");
       
       }
       else if(op1 == 2){
       ComandosTabla.setText("MODIFICAR REGISTRO nombre_tabla CLAVE valorCampoClave CAMPO campo POR valor_campo_nuevo");
       }
       else if(op1 == 3){
       ComandosTabla.setText("BORRAR REGISTRO nombre_tabla CLAVE valorCampoClave");
       } 
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEjecutar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JTextField ComandosTabla;
    private javax.swing.JList<String> ListaTablas;
    private javax.swing.JComboBox<String> SugerenciaRegistro;
    private javax.swing.JComboBox<String> SugerenciaTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JList<String> listascomando;
    private javax.swing.JLabel mensajesConsola;
    // End of variables declaration//GEN-END:variables
}
